### ISSUE TITLE
vec3.normalize() and invalid inputs

### ISSUE THREAD

**Issue by paulharris** [toji/gl-matrix#135]
Hi,

The code for vec3.normalize() does nothing to the output array if the input array can't be normalized (eg, if length of input vector = 0)

This means the calling method will experience inconsistent results based on whatever was in the output unit vector before the caller.

Can we add a line to at least set the output to (0,0,0) so that downstream code will hopefully get tripped up, rather than continuing with incorrect (but mathematically valid) results?

The code:
vec3.normalize = function(out, a) {
    var x = a[0],
        y = a[1],
        z = a[2];
    var len = x_x + y_y + z*z;
    if (len > 0) {
        //TODO: evaluate use of glm_invsqrt here?
        len = 1 / Math.sqrt(len);
        out[0] = a[0] \* len;
        out[1] = a[1] \* len;
        out[2] = a[2] \* len;
    }
    else {  // ADD THIS ELSE SCOPE
        out[0] = 0;  out[1] = 0; out[2] = 0;
    }
    return out;
};

**Comment by stefnotch** [comment]
Looks like this issue is still present in the latest version:
[vec2.js](https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/vec2.js#L322)
[vec3.js](https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/vec3.js#L346)
[vec4.js](https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/vec4.js#L370)

It can probably be "fixed" by changing
```js
if (len > 0) {
    //TODO: evaluate use of glm_invsqrt here?
    len = 1 / Math.sqrt(len);
    out[0] = a[0] * len;
    out[1] = a[1] * len;
}
```
to
```js
if (len > 0) {
    //TODO: evaluate use of glm_invsqrt here?
    len = 1 / Math.sqrt(len);
}
    out[0] = a[0] * len;
    out[1] = a[1] * len;

```
