### ISSUE TITLE
Add support for matrix decompose and compose

### ISSUE THREAD

**Issue by sanjayc77** [toji/gl-matrix#136]
Based on CSS3 transform spec: 

http://www.w3.org/TR/css3-transforms/#decomposing-a-3d-matrix
It also describes decomposing 2d matrix.

While we are at it, maybe support composing matrices given its component parts (translation, rotation, skew, perspective, etc).

Chromium also has an implementation in C++: 
https://github.com/ChromiumWebApps/chromium/blob/master/ui/gfx/transform_util.cc

**Comment by stefnotch** [comment]
These function have been implemented.

**Comment by gonnavis** [comment]
@stefnotch Hello, thank you very much for your work!

I saw `decompose` have been implemented, but `compose` not yet?

**Comment by stefnotch** [comment]
@gonnavis See https://glmatrix.net/docs/module-mat4.html#.fromRotationTranslationScale and other matrix functions. To compose them, you multiply them.

The only thing that I think isn't in there is `skew`. There was [a pull request](https://github.com/toji/gl-matrix/pull/293) to add it a while back, but nothing happened since then. I suppose skewing is a quite rare operation.

**Comment by gonnavis** [comment]
Thanks a lot!
