### ISSUE TITLE
Track matrix types in order to avoid unnecessary calculations.

### ISSUE THREAD

**Issue by mbebenita** [toji/gl-matrix#188]
In practice, many matrix operations operate on identity or translation only matrices. Keeping track of the current type of a matrix can help shortcut a lot of math. An example of this optimization can be seen here:

https://github.com/mozilla/shumway/blob/master/src/gfx/geometry.ts#L813

**Comment by toji** [comment]
This is a good goal, but I don't see how it could be applied to glMatrix in it's current form. It's an intentional choice by the library to not have a Mat4 class or a Vec3 class or any of the others. Instead any array-like object with at least the required number of elements is accepted. That means that `var v = [1, 2, 3];` is a totally valid glMatrix vector and can be passed to any of the `vec3.` functions. (This may change slightly as we shift to a SIMD-capable backend, which requires interaction with TypedArrays, but a glMatrix specific class will never be required.)

Given this design constraint I can't see how this kind of tracking would work. Sorry!

**Comment by mbebenita** [comment]
A `type` named property could be stored on matrix vectors. This would work for both Arrays and TypedArrays since they both support named properties, however it could potentially slow down Array access considerably.

Just a thought.

**Comment by toji** [comment]
You're right about the potential slow down. The severity differs from browser to browser, but in general dynamically attaching named properties to objects is a terrible thing to do if you're concerned about Javascript performance (which this library is).
