### ISSUE TITLE
Add double-precision variants of classes

### ISSUE THREAD

**Issue by neomantra** [toji/gl-matrix#192]
Javascript's native number type is double-precision floating point, whereas the gl-matrix classes are all single-precision.  As an original design decision, this makes sense since WebGL 1.0 and 2.0 only support Float32Array.   Thus, performing transformations in Javascript-space with single-precision floating point numbers lacks the precision afforded by the platform.

When porting our application to stack.gl (which has gl-matrix classes available), we noted quality regressions.  We were passing to `vec3` to `mat4.scale`; simply changing that `vec3` to `[x,y,z]` resolved it.  So this is a real use case.

I propose adding a set of classes like `mat4d`, `vec3d` that perform the same calculations (including SIMD support) of their single-precision floating point counterparts.  The naming parallels OpenGL convention.   So for clients that want to perform Javascript-space manipulations in 64-bit, using a well designed and familiar API, for as long as possible (i.e. before submitting as uniforms to shaders). 

The one drawback of this naming is that there is currently a `mat2d`.  I propose renaming this to `mat2D` and thus there can be a `mat2Dd` class.

I can do the work of implementing this, including tests.   But I was looking for feedback on the idea prior to embarking on it.

**Comment by toji** [comment]
This is something that has always been overridable. Just set `glMatrix.ARRAY_TYPE = Float64Array` or even just `glMatrix.ARRAY_TYPE = Array` and you'll get the behavior you want. This will prevent the SIMD path from being used, but since even 32 bit SIMD is still a work in progress I'd consider that out of scope for the time being.

**Comment by neomantra** [comment]
But that replaces the type globally.   The idea here was to have both types available in the API, giving flexibility to use the most appropriate type for one's circumstance.

**Comment by toji** [comment]
That replaces the type that `<type>.create()` and friends produce, but doesn't change anything about how the functions work. A consistent design decision of glMatrix since it's inception has been that the operations should be agnostic to the input types, as long as they're indexable and have the right number of elements. In this way the API is already extremely flexible:

```
var a = vec3.fromValues(1, 2, 3); // Float32Array by default
var b = [4, 5, 6];
var result = new Float64Array(3);

vec3.add(result, a, b); // Works just fine.
```

**Comment by neomantra** [comment]
Ah, that makes sense.  Thank you.
