### ISSUE TITLE
Doubt on "quat.rotate{X,Y,Z}" functions

### ISSUE THREAD

**Issue by MegaThomas** [toji/gl-matrix#219]
According to the [definition](https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation), quaternion rotation should be in the form of **q****p****q**^{-1}, where **q** is the rotation vector of [sin(θ/2)·**v**, cos(θ/2)], **v** is the axis of rotation, and **p** is the quaternion to be rotated. However, in the quat.rotate{X,Y,Z} functions, **pq** is calculated instead, which is only a half of the rotation. I doubt why it is implemented in this way.

**Comment by stefnotch** [comment]
@MegaThomas Either this issue has been resolved since you reported it or the /2 tripped you up.

`quat.rotateX(quat.create(), quat.create(), glMatrix.toRadian(360))`
returns: `Float32Array [ 0, 0, -0, -1 ]`
A 360 degree rotation should do nothing at all. And, this is exactly the case here, because [flipping all the signs of a quaternion does nothing](http://answers.ros.org/question/11790/can-z-value-in-quaternion-get-negative/)

Same test without an identity quaternion:
`quat.normalize(quat.create(),[1,0,0,2])`
`Float32Array [ 0.4472135901451111, 0, 0, 0.8944271802902222 ]`
`quat.rotateX(quat.create(), quat.normalize(quat.create(),[1,0,0,2]), glMatrix.toRadian(360))`
`Float32Array [ -0.4472135901451111, 0, -0, -0.8944271802902222 ]`

And a 90 degree rotation test:
`quat.rotateX(quat.create(), quat.create(), glMatrix.toRadian(90))`
returns: `Float32Array [ 0.7071067690849304, 0, 0, 0.7071067690849304 ]`
Which is correct because cos(90/2) == 0.7071067690849304

**Comment by stefnotch** [comment]
@toji This issue seems to be resolved.
