### ISSUE TITLE
Side effects of passing arrays instead of vectors?

### ISSUE THREAD

**Issue by bblack** [toji/gl-matrix#224]
For many (all?) functions that take vectors according to the docs, one can pass simple arrays instead:

```
var sum = vec3.add([], [1, 2, 3], [4,5,6]);
```

Is this supported? Are there side effects for performance or correctness?

**Comment by toji** [comment]
Yes, it is explicitly supported! No, there are no side effects for correctness. (Unless you've opt in to experimental SIMD support.)

There will be some impact to performance because you are creating and discarding several JavaScript objects, which always has some overhead. These type of allocations will get caught in the young generation garbage collection pass, though, so it's not too bad. Indexing a month typed array like this is probably a little slower too.

If you want the absolute best performance prefer preallocating and re-using typed arrays as much as possible. (vec3.create will give you the appropriate type) That being said, though, I wouldn't go crazy with that kind of optimization unless you know the code in question is a bottleneck.

**Comment by logixoul** [comment]
It would be nice to have this (arrays being able to be used as vectors) in the docs. Outside the function-per-function documentation, in some higher level conceptual "Usage" docs, I suppose.
