### ISSUE TITLE
Quaternion and Matrix multiplication order

### ISSUE THREAD

**Issue by stefnotch** [toji/gl-matrix#229]
The spec does not say in which order quaternions/matrices are multiplied.

For example, if I want to append a matrix (boneRot) to another one (worldRot), do I have to write:
`mat4.multiply(out, worldRot, boneRot)` or `mat4.multiply(out, boneRot, worldRot)`

**Comment by stefnotch** [comment]
After doing a bit of testing, it seems that the multiplications are backwards. (Code 2)
A bit unintuitive, in my opinion.

**Comment by httpdigest** [comment]
The spec does not say anything about matrix with quaternion multiplication order, because there is no such operation. Mathematically you cannot multiply a matrix with a quaternion. What you _can_ do though is converting a quaternion into its matrix form so that both represent the same transformation. And then do a matrix x matrix multiplication.

As for the order, it should be exactly how two matrices are multiplied. If `m` is a mat4, `n` is a mat4 which represents rotation `R` and `q` is a quat4 which represents the same rotation `R`, then the following equation should hold:
`m * n = m (x) q`

where `(x)` is the "matrix multiply-with quaternion" operation, which would just convert the quaternion into a mat4 representation, and then do a simple "matrix multiply-with matrix" operation.

If implemented correctly, it should never matter whether you use a matrix or a quaternion to represent a rotation transformation. Both should feel the same when applying operations to them involving either matrices or quaternions.

**Comment by stefnotch** [comment]
I meant: "Does not say anything about matrix multiplication order. It also does not say anything about Quaternion multiplication order."

**Comment by httpdigest** [comment]
Yes, I know that the order matters, thanks. However, you impose a "parent"/"child" relationship to those operations, which do not exist. The question is just, what the frame of reference is.
And with OpenGL, which uses matrix \* column-vector, post-multiplying a matrix `b` to the right of matrix `a` means applying the transformation represented by `b` relative to the local coordinate frame of `a`.
So, if you want to say that "parent" is the frame of reference for a "child" transformation, then it is:
`result = parentTransform * childTransform`

**Comment by stefnotch** [comment]
Oh, so it's just like in OpenGL?

(The parent-child thing was just an example, chosen because I currently am implementing skeletal animation)

**Comment by stefnotch** [comment]
Thanks a lot.
So, let's see if I got this right: This library uses a **column-major** layout but when typed out, it looks like row-major. (http://glmatrix.net/ A note about Matrix formatting)
And, it is **post multiplying** everything. 

(Which explains why I was confused and thought it was doing the multiplication backwards. I was passing row-major matrices to the functions.)

**Comment by Tomaz-Vieira** [comment]
I still think this is relevant to be mentioned in the documentation. `mat4.multiply(out, a, b)` has its parameters in the expected "mathematical expression" order (`out = a * b` i.e.: apply transformation `b`, then `a`) , but `vec3.transformMat3(out, a, m)`, which represents `out = m * a` doesn't, so I'd say it's a valid concern.

In fact, I'd say that "performs a * b" eliminates ambiguities and is far more informative than "Multiplies two mat4s" as a documentation string. 

Anyway, thanks for the great library!

**Comment by stefnotch** [comment]
The order in which your operations are applied depends on how you lay out your matrices, because ![`A * B = B^T * A^T`](https://wikimedia.org/api/rest_v1/media/math/render/svg/593d436fc05f4fc4f7efe8f1ea6cd89992d9d38f).

If you create two matrices using the glmatrix methods, like [`mat4.fromRotationTranslation`](https://glmatrix.net/docs/module-mat4.html#.fromRotationTranslation), then the matrices should be in the "programmer" order.
