### ISSUE TITLE
New Release Require

### ISSUE THREAD

**Issue by truelixin** [toji/gl-matrix#239]
I am using this library in IE8, and I found 'Float32Array not found' exception. Then I list the commit, and found that the problem has been fixed, so I require a new release for use.

**Comment by egoroof** [comment]
em, Float32Array comes in IE10 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array

**Comment by stefnotch** [comment]
@egoroof That isn't really a solution for his problem. 

@truelixin 
If you have Node.js set up, you could build it yourself. https://github.com/toji/gl-matrix/blob/master/BUILDING.md

Otherwise, you would have to wait until somebody does it for you. (If you absolutely need it right now, https://github.com/stefnotch/gl-matrix/tree/master/dist would work as a temporary solution. That is my dual quaternion branch...)

**Comment by truelixin** [comment]
Thanks.
