### ISSUE TITLE
community?

### ISSUE THREAD

**Issue by dakom** [toji/gl-matrix#265]
I'm just getting into webgl/3d math stuff and curious where some good community resources might be (slack, irc, forums, etc.)... feel free to close this as it's not an "issue", but I wasn't sure where else to ask ;)

**Comment by sannyi** [comment]
Try find it on https://www.opengl.org/discussion_boards/ and https://forums.khronos.org/.

**Comment by stefnotch** [comment]
Nope, forget those links. They are great if you want to learn OpenGL. However, WebGL is kinda different and has way cooler tutorials:
If you want to use WebGL 1
https://webglfundamentals.org/ 
Shiny new WebGL 2. However, it [isn't supported everywhere yet](https://caniuse.com/#search=webgl2). 
https://webgl2fundamentals.org/

**Comment by dakom** [comment]
Thanks! Yeah I see the pages and I'm learning :)

But I have kindof beginner/niche questions like why `translatedVector` here is [10,0] instead of [15,270]:

```
const originalVector = vec2.fromValues(10,200);
const translatedMatrix = mat2d.fromTranslation(mat2d.create(), vec2.fromValues(5, 70));
const translatedVector = vec2.multiply(vec2.create(), originalVector, translatedMatrix);
```

**Comment by stefnotch** [comment]
Oh, I'm not sure where those questions can/should be asked. 

About your question:
You are supposed to use `vec2.transformMat2d` instead of `vec2.multiply`.


@toji The API seems to trip up a lot of people. 
For example, quite a bunch of people want a function that multiplies a vector by a scalar....until they realize that `scale` does exactly that.
Another example is passing the wrong parameters to functions. (e.g. See above)

A debug version, which performs a lot of checks, of this library might be useful. Also, a basic tutorial would be really useful.

**Comment by dakom** [comment]
@stefnotch whoa, now it works :)

I'll have to take a look at the source to understand... I kinda want to get a better grip on how this all works, even if I do end up relying on the "magic" of `transformMat2d` ;)

**Comment by dakom** [comment]
oh I see... there's no "generic multiply", and the multiply for vec2 will ignore anything beyond the 2x2 values...
