### ISSUE TITLE
WebAssembly?

### ISSUE THREAD

**Issue by dakom** [toji/gl-matrix#280]
Given the popularity and target of gl-matrix, I'd imagine that a wasm port is on the radar... is that correct?

**Comment by maierfelix** [comment]
I'm currently working on a little 1:1 port without affecting the API conventions. First benchmarks already show good improvements! :)

**Comment by stefnotch** [comment]
https://github.com/toji/gl-matrix/issues/283

**Comment by Kevin-at-Navigram** [comment]
@dakom, @stefnotch Is a port of gl-matrix not redundent, because there already exists [OpenGL Mathematics](https://glm.g-truc.net/0.9.9/index.html)? Both even have the same acronym, glm.

It's also important to know that IO communication between JS and WebAssembly causes a lot of overhead. Unless you built the entire scene in WebAssembly and only sent it back once, there is no point of using GLM (whichever version) in WebAssembly.

**Comment by stefnotch** [comment]
@Kevin-at-Navigram 
Cool project. 👍 However, it still needs a WebAssembly bridge to be useful.

Regarding your performance concerns:
https://github.com/toji/gl-matrix/issues/283
