### ISSUE TITLE
Creating vec2's as Float32Arrays is 3x slower than plain js objects

### ISSUE THREAD

**Issue by distinctdan** [toji/gl-matrix#358]
I'm using gl-matrix for a game I'm building with a custom physics engine. Most of it is pretty simple math, like adding/multiplying vectors. However, I'm finding that gl-matrix's way of creating vectors as Float32Arrays is way slower than using plain js objects. Since I'm using it for a lot of intermediate steps, I can't reuse any of the vectors, so I'm losing performance. Some of these low level physics functions are called thousands of times a second; enough that I've noticed the performance hit while profiling.

Here's an example function:
```
export function getClosestTOnLine(p1: Float32Array, p2: Float32Array, c: Float32Array): IPathPoint {
    // Do dotProduct/magnitude
    const p1ToC = vec2.fromValues(c[0] - p1[0], c[1] - p1[1]);
    const p1ToP2 = vec2.fromValues(p2[0] - p1[0], p2[1] - p1[1]);
    const lenSqrd = vec2.sqrDist(p1, p2);
    const t = lenSqrd > 0
        ? vec2.dot(p1ToC, p1ToP2)/lenSqrd
        : 0;
    return {t: t, subindex: 0};
}
```

A performance test shows plain objects are 3x faster to create for a simple case like this:
https://jsperf.com/gl-matrix-vec2-float32array-vs-plain-objects

For me, unfortunately this means I'm planning on removing gl-matrix wherever possible to save performance, and using an object based style instead. I realize this is a big architectural decision and it may never change, but wanted to provide feedback that may influence future versions.

**Comment by stefnotch** [comment]
### My canonical response to the age old Float32Array vs Objects discussion

Yes, creating `Float32Arrays` has a significant performance overhead. However, as the name glMatrix already implies, this library is designed for usage with WebGL, which requires you to convert everything to Float32Arrays. This is pretty much the main reason behind using Float32Arrays by default.

You can switch to creating normal JavaScript arrays by [calling `glMatrix.setMatrixArrayType(Array)`](http://glmatrix.net/docs/common.js.html#line16). Normal JavaScript arrays are usually much cheaper to create.

To get the maximum performance out of glMatrix, reusing and caching Float32Arrays is highly encouraged. For example, instead of creating a new Float32Array every method call, only 1 needs to be created outside of the method and re-used every time. Since JavaScript is single threaded, this optimization is perfectly fine.

I took the liberty of rewriting your example to take advantage of this. 
https://jsperf.com/glmatrix-getclosesttonline/
As of writing this, that simple optimisation makes glMatrix with Float32Arrays faster than a library that uses objects.




Previous places where this was discussed
- https://github.com/toji/gl-matrix/issues/11
- https://github.com/toji/gl-matrix/issues/99#issuecomment-30673514

**Comment by distinctdan** [comment]
Thanks for the response. That's an interesting idea creating separate persistent variables for each function. It's ugly, but it is certainly faster, even than objects. Given the performance boost, I'll definitely look into doing this instead.

Yeah, if you guys are going for opengl support, I can see the rationale for using arrays. I'm using another library (pixi.js) to abstract out the opengl stuff, so I'm not directly interacting with it.

I was curious, so I expanded your example to include a test that didn't use objects or arrays at all, and I was surprised that it was faster than all the others by a factor of 10x: https://jsperf.com/glmatrix-getclosesttonline/5. However, that's not always practical because using a library of some sort greatly improves readability and conciseness of the code, so I'm still inclined to use one in all but the most performance intensive places.

Thanks for the help, I'll go ahead and close this.

**Comment by distinctdan** [comment]
Another small thought, I believe your arrays example would actually be even faster than this test shows, because if you were using objects, you'd likely be using an objects-based vector library instead of doing the add/subtracts yourself, so you'd have the additional overhead of a function call to that library to do your vector stuff.

**Comment by stefnotch** [comment]
> It's ugly, but it is certainly faster

Yeah, I wish JS JIT compilers were smart enough to do that optimisation for you.

> and I was surprised that it was faster than all the others by a factor of 10x: https://jsperf.com/glmatrix-getclosesttonline/5. 

Wow, thanks for that benchmark. I knew that inlining maths and using local variables does provide a performance boost but I didn't know that it's such an enormous one.

> However, that's not always practical because using a library of some sort greatly improves readability and conciseness of the code, so I'm still inclined to use one in all but the most performance intensive places.

I wonder if you could use a transpiler to do those optimisations for you. Then you would have the best of both worlds: Readable code and lightning fast performance.

**Comment by distinctdan** [comment]
That's an interesting idea about transpilation. I'm using grunt in my build process, and I already do some basic templating to substitute in things like build version and asset paths. However, I'm also using typescript, so for anything that goes outside of typescript world, I would lose type safety. It sure would be nice if javascript supported something like compiler macros, or the ability to auto-inline stuff.
