### ISSUE TITLE
set() vs fromValues()

### ISSUE THREAD

**Issue by z3dev** [toji/gl-matrix#417]
For consistency sake, only one of these needs to be present, as the fromValues() should also have an 'out' parameter, just like all the other from* functions.

`vec3.fromValues(out, x, y, z)`

After this change, set() is redundant.

**Comment by toji** [comment]
`.fromValues()` creates a new vector, while `.set()` changes the values of an existing vector, which is why it requires an `out` parameter. (The 'fromMat/Quat/etc` functions are different in that they convert between types.) Given that they serve two different purposes, we should keep the methods separate.
